spring:
  application:
    name: jaebichuri

  datasource:
    url: jdbc:postgresql://localhost:5432/jaebichuri
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    groups-order: DESC
    operations-sorter: method
  cache:
    disabled: true
